export const TOPICS = [
    "Innovation",
    "Technology",
    "Sustainability",
    "AI & Machine Learning",
    "Health",
    "Education",
    "Food",
    "Transport",
    "Fashion",
    "Art",
    "Music",
    "Film",
    "Literature",
    "Sports",
    "Energy",
    "Cybersecurity",
    "Space",
    "Ocean",
    "Investments",
    "Climate",
    "Environment",
    "Economy",
    "Politics",
    "Culture",
    "Science",
    "Technology",
    "Artificial Intelligence",
    "Machine Learning",
    "Blockchain",
    "Cryptocurrency",
    "FinTech",
    "HealthTech",
    "EducationTech",
    "FoodTech",
    "TransportTech",
    "FashionTech",
    "ArtTech",
    "MusicTech",
    "FilmTech",
    "LiteratureTech",
    "SportsTech",
    "EnergyTech",
    "CybersecurityTech",
    "SpaceTech",
    "OceanTech",
]

export const PLACEHOLDERS = {
    name: "Your Name",
    title: "Your Title",
    topic: "What would you like to discuss?"
}