import type { Metadata } from "next";
import { displayFont, bodyFont } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${displayFont.variable} ${bodyFont.variable}`}
      data-oid="m1397_8"
    >
      <body data-oid="y.zev82">{children}</body>
    </html>
  );
}
